corrected script/build files

diff --git a/appSrc/Allwmake b/appSrc/Allwmake
--- a/appSrc/Allwmake
+++ b/appSrc/Allwmake
@@ -1,8 +1,8 @@
 #!/bin/sh
 cd ${0%/*} || exit 1    # run from this directory
 
-wmakeCheckPwd "$WM_PROJECT_USER_DIR/FC-APOLLO/appSrc" || {
-    echo "Error: Current directory is not \$WM_PROJECT_USER_DIR/FC-APOLLO/appSrc"
+wmakeCheckPwd "$WM_PROJECT_USER_DIR/FCAPOLLO/appSrc" || {
+    echo "Error: Current directory is not \$WM_PROJECT_USER_DIR/FCAPOLLO/appSrc"
     echo "    The environment variables are inconsistent with the installation."
     echo "    Check the OpenFOAM entries in your dot-files and source them."
     exit 1
